### ISSUE TITLE
Issue while deploying BcdrOnPrem template

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-Business-continuity-and-disaster-recovery#43]
In exercise 1 Task 2 while deploying BcdrOnPrem template custom script is getting failed , so as a workaround i tried setting the powershell version to tls1.2 and it worked

**Comment by Rupaliss** [comment]
This HOL doesn't seem to work, the OnPrem, deployment doesn't deploy OnPremVM (LAMP) within the HyperV. During the JSON deployment, after 1.5 hours it fails as HyperV extension stays in Transition status, hence deployed manually, but that does not bring the LAMP Server

IaaS Deployment, unable to Add cluster node 3, says could not find the node SQLVM3, when its deployed in Secondary region.
Trying to setup with this since last 1 week, Lot of complexity

**Comment by akn9050** [comment]
If you use win server 2019 and following install-hyper-v script in custom script then it will work. It is because recent security protocol changes in latest marketplace win vm images. We need to enable TLS 1.2 before installing the nuget package

Install Hyper V script for on-prem vm custom script extension:  
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord

Install-PackageProvider -Name NuGet -Verbose -Force
sleep 5
Find-Module -Includes DscResource -Name xHyper-v
sleep 2
Install-Module -Name xHyper-v -Force -Verbose
sleep 3
# Install Hyper-V and reboot
Write-Output "Install Hyper-V and restart"
Stop-Transcript
Install-WindowsFeature -Name Hyper-V -IncludeManagementTools -Restart

**Comment by crpietschmann** [comment]
This issue was caused by a change that was made to the Windows Server VM image used from the marketplace. The fix was to add some code to the `InstallHyperV.ps1` PowerShell script that enables TLS 1.2 strong cryptography in .NET Framework 4.5 or higher.

A reference of the registry keys to set for this fix are found here: https://docs.microsoft.com/en-us/officeonlineserver/enable-tls-1-1-and-tls-1-2-support-in-office-online-server#enable-strong-cryptography-in-net-framework-45-or-higher

This issue has now been fixed. @himanshuahlawat31 thanks for submitting this Issue, and thanks @akn9050 for submitting a suggestion for fixing the issue.
